my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('users.urls'))
]

my_project/users/urls.py
from django.urls import path, include
from users import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView

app_name = "users"
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("change_password/", PasswordChangeView.as_view(
    template_name="registration/change_form.html",
    success_url="done/"), name="change"
    ),
    path("change_password/done/", PasswordChangeDoneView.as_view(template_name="registration/change_done.html"), name="change_done"),
    path("reset_password/", PasswordResetView.as_view(
        template_name = "registration/reset_password_form.html",
        success_url = "done/"), name="reset")
]

my_project/users/models.py
from django.db import models


my_project/users/views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, "users/dashboard.html")

my_project/users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    {% block title %}
        <title>Document</title>
    {% endblock %}
</head>
<body>
    {% block heading %}
        <h1>My cute site</h1>
        <br>
    {% endblock %}

    {% block content %}
    {% endblock %}
</body>
</html>

my_project/users/templates/users/dashboard.html
{% extends 'base.html' %}

{% block content %}
    Hello, {{ user.username|default:'Guest' }}!

<div>
    {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}">Logout</a>
        <a href="{% url 'users:change' %}">Change password</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
        <a href="{% url 'users:reset' %}">Reset password</a>
    {% endif %}
</div>

{% endblock %}